### ISSUE TITLE
Bot crashes when receiving 429 from RootMe

### ISSUE THREAD

**Issue by ctmbl** [iScsc/RootPythia#18]
#8 introduces the API manager adn the rate limiter which is supposed to try a configured number of time each request until it gets a 200.
However for some reason the main task teardown isn't done well and can end up in a crash if looping:
```
2023-06-22 20:27:40 INFO     bot.root_pythia_cogs Checking for new solves...
2023-06-22 20:27:42 WARNING  api.rate_limiter Request : GET https://api.www.root-me.org//auteurs/706764 + {'api_key': 'CENSORED'} failed with response code 429
2023-06-22 20:27:44 ERROR    asyncio Task exception was never retrieved
future: <Task finished name='Task-10' coro=<RateLimiter.handle_requests() done, defined at /opt/root-pythia/src/api/rate_limiter.py:43> exception=ValueError('task_done() called too many times')>
Traceback (most recent call last):
  File "/opt/root-pythia/src/api/rate_limiter.py", line 108, in handle_requests
    self.queue.task_done()
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 202, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times
```

**HYPOTHESES**:
Problematically, if the rate limiter loop crashes, we can't ever make request, so even if the bot still works it can't fetch root me API
at least this is how I understand the situation so far
this isn't tested but on a crash it shouldn't respond to `!adduser` nor `!getuser` but should respond to `!ping` 

This is particularly bad because the check_for_new_solves loop is configured to automatically restart on crash but not the rate limiter loop
a `!status` command would be great
a bit more verbosity would be good too

**Comment by ctmbl** [comment]
another really important point:
this would have been easily avoided if it woiuld have been tested so I suggest we write unit test for the rate limiter and api manager classes, at least here a regression test

**Comment by atxr** [comment]
I think there might be a problem here
```py
    async def handle_requests(self):
        self.logger.info("Starting rate_limiter task...")

        # local variable
        last_time_request = datetime.now()
        retry = False
        retry_count = 0

        while True:
            # take a new request from the queue
            if not retry:
                request = await self.queue.get()
                self.logger.debug(
                    "Treating item in queue : %s -> %s + %s ",
                    request.key,
                    request.url,
                    request.cookies,
                )
                retry_count = 0
            else:
                # request stays the same
                self.logger.debug(
                    "Retrying %s item in queue : %s -> %s + %s ",
                    retry_count,
                    request.key,
                    request.url,
                    request.cookies,
                )
                retry = False

            # wait 50ms for rate limitation purpose ;)
            loop_duration = (datetime.now() - last_time_request).total_seconds()
            if (0.050 - loop_duration) > 0.01:
                await asyncio.sleep(0.050 - loop_duration)

            if request.method == "GET":
                # keep track of the last time a request was made
                last_time_request = datetime.now()
                # actually send the GET request
                resp = requests.get(request.url, cookies=request.cookies)
                if resp.status_code != 200:
                    self.logger.warning(
                        "Request : GET %s + %s failed with response code %s",
                        request.url,
                        request.cookies,
                        resp.status_code,
                    )
                    if retry_count < self._max_retry:
                        retry = True
                        retry_count += 1

                        ###
                        # Imagine we are in this case (429 code for example)
                        # Here we doesn't do `continue` so we will end up calling self.queue.task_done()
                        # even if the request failed
                        ###

                    else:
                        self.logger.error(
                            "Failed to get request after %s attempt. We could be banned :(",
                            self._max_retry,
                        )
                        raise RuntimeError("Looks like a ban to me :'(")
                else:
                    data = resp.json()
            else:
                raise NotImplementedError("Only GET method implemented for now.")

            # we send back the response and trigger the event of this request
            self.requests[request.key]["result"] = data
            self.requests[request.key]["event"].set()

            ###
            # So now we called set on the event, but in our scenario WE SHOULDN'T because we will retry
            # and call `set` again during the next loop (this will crash)
            ###

            # finally we inform the queue of the end of the process
            self.queue.task_done()
```

**Comment by ctmbl** [comment]
@atxr this is exactly, but much more precisely, what I was thinking!

**Comment by atxr** [comment]
The PR is ready then 😉

**Comment by ctmbl** [comment]
@atxr see #19  not really :wink:
