### ISSUE TITLE
Can't find `!add` command after trying to invoke non implemented `!help` command

### ISSUE THREAD

**Issue by Turtyo** [iScsc/RootPythia#33]
After trying to use the `!help` command ( which is yet to be merged with #30 ), the bot gives an error because the command doesn't exist (normal). When trying to use the `!add` command just after, the bot is unable to find the command (but the command exists, so it should find it).

Logs:
```py
2023-10-10 09:14:27 ERROR    bot.root_pythia_cogs 'help' command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/help.py", line 948, in command_callback
    return await self.send_bot_help(mapping)
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/help.py", line 1257, in send_bot_help
    note = self.get_ending_note()
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/help.py", line 1070, in get_ending_note
    f'Type {self.context.clean_prefix}{command_name} command for more info on a command.\n'
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/context.py", line 422, in clean_prefix
    pattern = re.compile(r"<@!?%s>" % user.id)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/root-pythia/src/bot/root_pythia_cogs.py", line 128, in on_command_error
    raise error
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
2023-10-10 09:18:38 INFO     bot.root_pythia_cogs Checking for new solves...
2023-10-10 09:23:38 INFO     bot.root_pythia_cogs Checking for new solves...
2023-10-10 09:24:06 ERROR    bot.root_pythia_cogs 'None' command failed
Traceback (most recent call last):
  File "/opt/root-pythia/src/bot/root_pythia_cogs.py", line 128, in on_command_error
    raise error
discord.ext.commands.errors.CommandNotFound: Command "add" is not found
2023-10-10 09:25:03 ERROR    bot.root_pythia_cogs 'None' command failed
Traceback (most recent call last):
  File "/opt/root-pythia/src/bot/root_pythia_cogs.py", line 128, in on_command_error
    raise error
 ```

**Comment by ctmbl** [comment]
we're just dumb as f***, since the `!help` command wasn't implemented yet (#30 not merged at the time) we were just trying the wrong command (`!add` instead of `!adduser`) and thinking the previous `!help` had break the bot...
There's no bug just a bunch of idiots (us)

Closing this one then :slightly_smiling_face:
